apiVersion: v2
actions:
  - name: "Run k6"
    events:
      - name: "sh.keptn.event.remote-passing-task.triggered"
    tasks:
      - name: "Run k6 with Keptn"
        files:
          - files/k6
        image: "loadimpact/k6"
        cmd: ["k6"]
        args: ["run", "--duration", "30s", "--vus", "10", "/keptn/files/k6/passing_threshold.js"]